### ISSUE TITLE
Formal release?

### ISSUE THREAD

**Issue by Mark-H** [poconosewandvac/Commerce_AbandonedCart#2]
What would it take for this extension to be officially released as an installable package? The readme sounds like it's already working fabulously. ;)

**Comment by tonyklapatch** [comment]
I think it is pretty much ready for release, I'll need to retest on the latest version of Commerce to make sure everything is working correctly.

I also wanted to implement some events such as:

- USER_SUBSCRIBE (before/after)
- USER_UNSUBSCRIBE (before/after)
- MESSAGE_SEND (before/after)

To allow for 3rd party modules to hook into this, however that could be added in a 1.1.0 release.
