### ISSUE TITLE
Link to abandon cart

### ISSUE THREAD

**Issue by crimsonpixel** [poconosewandvac/Commerce_AbandonedCart#5]
I've added this extra to Commerce however, a couple of issues.  Firstly when I initially added it, the directory commerce_abandonedcart was not created under the assets folder nor the files, so the cron job couldn't run.  I created these manually and that worked.

Secondly, the test email is fine however, there is no link back to restore the cart.  Typically when a customer has abandoned a cart they don't want to go through the process of adding the products again and simply want to click to a restored cart and be able to place the order.  How can this be added?

Also it seemed to cause a bit of an issue with orders being placed moving from Draft to Payment Received which resulted in the notifications not being sent.  Not sure whether this was an issue linked with the cronjob not running in the first place.

**Comment by tonyklapatch** [comment]
I've added a new "restore_link" Twig variable in the new release 1.0.1-pl, see the updated example template:  https://github.com/poconosewandvac/Commerce_AbandonedCart/blob/master/core/components/commerce_abandonedcart/templates/abandonedcart/emails/standard.twig#L42 

This also fixes the other issues with order placement with this module.
