### ISSUE TITLE
Can not view Customers tab

### ISSUE THREAD

**Issue by chenrupo** [poconosewandvac/Commerce_AbandonedCart#6]
Getting this error when trying to view the Customers tab:
An exception occurred generating the page
Exception: Twig\Error\LoaderError: Template "abandonedcart/admin/widgets/customer-info.twig" is not defined.

Any ideas what might be going on?

**Comment by tonyklapatch** [comment]
Fixed in the new 1.0.1-pl release, as well as other issues with assets not deploying.
