### ISSUE TITLE
Fatal error in convertAbandonedCartToProcessing causing order processing to fail

### ISSUE THREAD

**Issue by Mark-H** [poconosewandvac/Commerce_AbandonedCart#7]
> Fatal error: Uncaught TypeError: Argument 1 passed to PoconoSewVac\AbandonedCart\Modules\AbandonedCart::convertAbandonedCartToProcessing() 
> must be an instance of modmore\Commerce\Events\Payment, instance of modmore\Commerce\Events\OrderState given, 
> called in core/components/commerce/vendor/symfony/event-dispatcher/EventDispatcher.php on line 184 and defined in core/components/commerce_abandonedcart/src/Modules/AbandonedCart.php:163 
> 
> Stack trace: 
>
> #0 core/components/commerce/vendor/symfony/event-dispatcher/EventDispatcher.php(184): PoconoSewVac\AbandonedCart\Modules\AbandonedCart->convertAbandonedCartToProcessing(Object(modmore\Commerce\Events\OrderState), 'core.order-stat...', Object(Symfony\Component\EventDispatcher\EventDispatcher)) 
> #1 core/components/commerce/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispat in core/components/commerce_abandonedcart/src/Modules/AbandonedCart.php on line 163

Commerce 1.2.5, abandoned cart 1.0.0-pl

Simply tweaking the parameter type seems to do the trick without further changes.

**Comment by tonyklapatch** [comment]
Resolved in #4 - will be pushing up a new package to MODX.com today for all the fixes on this. Thanks Mark!
